services:
  db:
    image: postgres:16
    container_name: mvc_1
    environment:
      POSTGRES_DB: mvc
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    restart: unless-stopped